name: check_stocks

on:
    schedule:
        # Runs everyday at:
        # 12:15 AM UTC (GMT0:00) -> 06:00 AM Nepal Time (GMT+5:45)
        - cron: "15 00 * * *"

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Add new stocks & publish to telegram channel
              env:
                  ALLOTMENT_URL: ${{ secrets.ALLOTMENT_URL }}
                  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
                  NEWS_URL_BM: ${{ secrets.NEWS_URL_BM }}
                  NEWS_URL_ML: ${{ secrets.NEWS_URL_ML }}
                  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
                  CHANNEL: ${{ secrets.CHANNEL }}
                  REFERER: ${{ secrets.REFERER }}
                  API_URL: ${{ secrets.API_URL }}
                  PDF_URL: ${{ secrets.PDF_URL }}
                  ORIGIN: ${{ secrets.ORIGIN }}
              run: |
                  python main.py

            - name: Commit only if new stocks have been added
              run: |
                  git config --global user.email "stonksbot@example.com"
                  git config --global user.name "stonksbot"
                  git diff --quiet || (git add nepstonks.db && git commit -m "ðŸŒ± db: add new stocks")
                  git push origin HEAD:main
